name : Kotlin CI

on :
  push :
    branches :
      - main
  pull_request :
    paths-ignore :
      # Don't build the entire app when just changing tutorials, which have their own workflow.
      - 'samples/tutorial/**'

jobs :

  cancel-stale-jobs :
    runs-on : ubuntu-latest
    steps :
      # If CI is already running for a branch when that branch is updated, cancel the older jobs.
      - name : Cancel Stale Jobs
        uses : styfle/cancel-workflow-action@0.9.1
        env :
          GITHUB_TOKEN : '${{ secrets.GITHUB_TOKEN }}'

  dokka :
    name : Assemble & Dokka
    runs-on : ubuntu-latest
    timeout-minutes : 20
    steps :
      - uses : actions/checkout@v3
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution: 'zulu'
          java-version : 11

      ## Actual task
      - uses: gradle/gradle-build-action@v2
        name : Assemble with gradle — make sure everything builds
        with :
          arguments : |
            assemble --stacktrace
          cache-read-only: false

      # This should ideally be done as a Check job below, but it needs to be done as a separate
      # step after running assemble. Heckin' ridikalus.
      # Probably fixed in dokka 1.4.10, but we can't move to kotlin 1.4 yet.
      #  https://github.com/square/workflow/issues/1152.
      - uses: gradle/gradle-build-action@v2
        name : Run dokka to validate kdoc
        with :
          arguments : |
            siteDokka --build-cache --stacktrace
          cache-read-only: false

  # These are all pretty quick so we run them on a single shard. Fewer shards, less queueing.
  check :
    name : Check
    runs-on : ubuntu-latest
    timeout-minutes : 20
    steps :
      - uses : actions/checkout@v3
      - uses : gradle/wrapper-validation-action@v1
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution: 'zulu'
          java-version : 11

      ## Actual task
      - uses: gradle/gradle-build-action@v2
        name : Check with Gradle
        with :
          arguments : |
            check apiCheck checkVersionIsSnapshot artifactsCheck dependencyGuard lint ktlintCheck jvmWorkflowNodeBenchmarkJar --stacktrace --continue
          cache-read-only: false

      # Report as Github Pull Request Check.
      - name : Publish Test Report
        uses : mikepenz/action-junit-report@v3
        if : always() # always run even if the previous step fails
        with :
          report_paths : '**/build/test-results/test/TEST-*.xml'

  jvm-timeout-runtime-test:
    name: Frame Timeout Runtime JVM Tests
    runs-on : ubuntu-latest
    timeout-minutes : 20
    steps :
      - uses : actions/checkout@v3
      - uses : gradle/wrapper-validation-action@v1
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution: 'zulu'
          java-version : 11

      ## Actual task
      - uses: gradle/gradle-build-action@v2
        name : Check with Gradle
        with :
          arguments : |
            jvmTest --stacktrace --continue -Pworkflow.runtime=timeout
          cache-read-only: false

      # Report as Github Pull Request Check.
      - name : Publish Test Report
        uses : mikepenz/action-junit-report@v3
        if : always() # always run even if the previous step fails
        with :
          report_paths : '**/build/test-results/test/TEST-*.xml'

  ios-tests :
    name : iOS Tests
    runs-on : macos-latest
    timeout-minutes : 30
    steps :
      - uses : actions/checkout@v3
      - uses : gradle/wrapper-validation-action@v1
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution: 'zulu'
          java-version : 11

      ## iOS Specific Tests (for KMP ios actuals in core and runtime).
      - uses: gradle/gradle-build-action@v2
        name : Check with Gradle
        with :
          arguments : |
            iosX64Test --stacktrace
          cache-read-only: false

      ## iOS Specific Tests w/ strict memory model (for KMP ios actuals in core and runtime).
      - uses: gradle/gradle-build-action@v2
        name : Check with Gradle
        with :
          arguments : |
            iosX64Test -Pkotlin.native.binary.memoryModel=strict --stacktrace
          cache-read-only: false

      # Report as Github Pull Request Check.
      - name : Publish Test Report
        uses : mikepenz/action-junit-report@v3
        if : always() # always run even if the previous step fails
        with :
          report_paths : '**/build/test-results/test/TEST-*.xml'

  js-tests :
    name : JS Tests
    runs-on : macos-latest
    timeout-minutes : 30
    steps :
      - uses : actions/checkout@v3
      - uses : gradle/wrapper-validation-action@v1
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution : 'zulu'
          java-version : 11

      ## JS Specific Tests (for KMP js actuals in core and runtime).
      - uses : gradle/gradle-build-action@v2
        name : Check with Gradle
        with :
          arguments : |
            jsTest --stacktrace
          cache-read-only : false

      # Report as Github Pull Request Check.
      - name : Publish Test Report
        uses : mikepenz/action-junit-report@v3
        if : always() # always run even if the previous step fails
        with :
          report_paths : '**/build/test-results/test/TEST-*.xml'

  performance-tests :
    name : Performance tests
    runs-on : macos-latest
    timeout-minutes : 30
    strategy :
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast : false
      matrix :
        api-level :
          - 29
      # Unclear that older versions actually honor command to disable animation.
      # Newer versions are reputed to be too slow: https://github.com/ReactiveCircus/android-emulator-runner/issues/222
    steps :
      - uses : actions/checkout@v3
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution : 'zulu'
          java-version : 11

      ## Build before running tests, using cache.
      - uses: gradle/gradle-build-action@v2
        name : Build instrumented tests
        with :
          arguments : |
            :benchmarks:performance-poetry:complex-poetry:assembleDebugAndroidTest --stacktrace
          cache-read-only: false

      ## Actual task
      - name : Render Pass Counting Test
        uses : reactivecircus/android-emulator-runner@v2
        with :
          # @ychescale9 suspects Galaxy Nexus is the fastest one
          profile : Galaxy Nexus
          api-level : ${{ matrix.api-level }}
          arch : x86_64
          # Skip the benchmarks as this is running on emulators
          script : ./gradlew :benchmarks:performance-poetry:complex-poetry:connectedCheck --stacktrace --continue

      - name : Upload results
        if : ${{ always() }}
        uses : actions/upload-artifact@v3
        with :
          name : instrumentation-test-results-${{ matrix.api-level }}
          path : ./**/build/reports/androidTests/connected/**

  instrumentation-tests :
    name : Instrumentation tests
    runs-on : macos-latest
    timeout-minutes : 45
    strategy :
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast : false
      matrix :
        api-level :
          - 29
      # Unclear that older versions actually honor command to disable animation.
      # Newer versions are reputed to be too slow: https://github.com/ReactiveCircus/android-emulator-runner/issues/222
    steps :
      - uses : actions/checkout@v3
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution: 'zulu'
          java-version : 11

      ## Build before running tests, using cache.
      - uses: gradle/gradle-build-action@v2
        name : Build instrumented tests
        with :
          arguments : |
            assembleDebugAndroidTest --stacktrace
          cache-read-only: false

      ## Actual task
      - name : Instrumentation Tests
        uses : reactivecircus/android-emulator-runner@v2
        with :
          # @ychescale9 suspects Galaxy Nexus is the fastest one
          profile : Galaxy Nexus
          api-level : ${{ matrix.api-level }}
          arch : x86_64
          # Skip the benchmarks as this is running on emulators
          script : ./gradlew connectedCheck -x :benchmarks:dungeon-benchmark:connectedCheck -x :benchmarks:performance-poetry:complex-benchmark:connectedCheck -x :benchmarks:performance-poetry:complex-poetry:connectedCheck --stacktrace

      - name : Upload results
        if : ${{ always() }}
        uses : actions/upload-artifact@v3
        with :
          name : instrumentation-test-results-${{ matrix.api-level }}
          path : ./**/build/reports/androidTests/connected/**

  frame-timeout-instrumentation-tests :
    name : Frame Timeout Instrumentation tests
    runs-on : macos-latest
    timeout-minutes : 45
    strategy :
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast : false
      matrix :
        api-level :
          - 29
      # Unclear that older versions actually honor command to disable animation.
      # Newer versions are reputed to be too slow: https://github.com/ReactiveCircus/android-emulator-runner/issues/222
    steps :
      - uses : actions/checkout@v3
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          distribution : 'zulu'
          java-version : 11

      ## Build before running tests, using cache.
      - uses: gradle/gradle-build-action@v2
        name : Build instrumented tests
        with :
          # Unfortunately I don't think we can key this cache based on our project property so
          # we clean and rebuild.
          arguments : |
            clean assembleDebugAndroidTest --stacktrace -Pworkflow.runtime=timeout
          cache-read-only: false

      ## Actual task
      - name : Instrumentation Tests
        uses : reactivecircus/android-emulator-runner@v2
        with :
          # @ychescale9 suspects Galaxy Nexus is the fastest one
          profile : Galaxy Nexus
          api-level : ${{ matrix.api-level }}
          arch : x86_64
          # Skip the benchmarks as this is running on emulators
          script : ./gradlew connectedCheck -x :benchmarks:dungeon-benchmark:connectedCheck -x :benchmarks:performance-poetry:complex-benchmark:connectedCheck -x :benchmarks:performance-poetry:complex-poetry:connectedCheck --stacktrace -Pworkflow.runtime=timeout

      - name : Upload results
        if : ${{ always() }}
        uses : actions/upload-artifact@v3
        with :
          name : instrumentation-test-results-${{ matrix.api-level }}
          path : ./**/build/reports/androidTests/connected/**

  upload-to-mobiledev :
    name : mobile.dev | Build & Upload
    runs-on : ubuntu-latest
    timeout-minutes : 20
    steps :
      - uses : actions/checkout@v3

      - name : set up JDK 11
        if : env.MOBILE_DEV_API_KEY != null
        uses : actions/setup-java@v3
        with :
          distribution: 'zulu'
          java-version : 11
        env :
          MOBILE_DEV_API_KEY : ${{ secrets.MOBILE_DEV_API_KEY }}


      ## Build artifact for upload with cache
      - uses: gradle/gradle-build-action@v2
        name : Build Performance Poetry APK
        if : env.MOBILE_DEV_API_KEY != null
        with :
          arguments : |
            benchmarks:performance-poetry:complex-poetry:assembleRelease --stacktrace
          cache-read-only: false
        env :
          MOBILE_DEV_API_KEY : ${{ secrets.MOBILE_DEV_API_KEY }}

      ## Upload with POST
      - name : Upload Poetry to mobile.dev
        if : env.MOBILE_DEV_API_KEY != null
        id : upload_apk
        run : |
          #!/usr/bin/env bash
          set -e
          set -x
          RESPONSE_ID=$(curl -X POST \
            -H 'Content-Type: multipart/form-data' \
            -H "Authorization: Bearer $MOBILE_DEV_API_KEY" \
            --data-binary "@$APP_FILE" \
            https://api.mobile.dev/apk | jq -r .id)
          echo "::set-output name=apk_id::$RESPONSE_ID"
        env :
          MOBILE_DEV_API_KEY : ${{ secrets.MOBILE_DEV_API_KEY }}
          APP_FILE : benchmarks/performance-poetry/complex-poetry/build/outputs/apk/release/complex-poetry-release.apk

      ## Start analysis
      - name : Start analysis on mobile.dev
        if : env.MOBILE_DEV_API_KEY != null
        run : |
          #!/usr/bin/env bash
          set -e
          set -x
          GIT_HASH=$(git log --pretty=format:'%h' -n 1)
          BENCHMARK_NAME="$GIT_HASH"
          REPO_BASE_NAME=$(basename "$REPO_NAME")
          if [[ ! -z "$PULL_REQUEST_ID" ]]; then
            PR_DATA=", \"repoOwner\":\"$REPO_OWNER\", \"repoName\":\"$REPO_BASE_NAME\", \"pullRequestId\":\"$PULL_REQUEST_ID\""
          fi
          curl -X POST \
           -H "Content-Type: application/json" \
           -H "Authorization: Bearer $MOBILE_DEV_API_KEY" \
           https://api.mobile.dev/analysis \
           --data "{\"benchmarkName\": \"$BENCHMARK_NAME\", \"apkId\": \"$APP_ID\", \"branch\": \"$BRANCH_NAME\"$PR_DATA}"
        env :
          APP_ID : ${{ steps.upload_apk.outputs.apk_id }}
          MOBILE_DEV_API_KEY : ${{ secrets.MOBILE_DEV_API_KEY }}
          REPO_OWNER : ${{ github.repository_owner }}
          REPO_NAME : ${{ github.repository }}
          BRANCH_NAME : ${{ github.head_ref || github.ref_name }}
          PULL_REQUEST_ID : ${{ github.event.pull_request.number }}
